### ISSUE TITLE
Exception when running summary on U-Net model

### ISSUE THREAD

**Issue by maronsson** [TylerYep/torchinfo#100]
**Describe the bug**
I implemented a U-Net model based on the 2015 article and some googling. 
Seems to work ok but summary produce an exception.
Have used summary on multiple networks and it is great, thank you all for this project! 
I don't understand the error message, something about type mismatch.

**To Reproduce**
1. Save attached python file to disk
2. Run python unet_2015.py
3. See error

**Expected behavior**
Information about the network, such as number of parameters total and for each layer.

**Screenshots**
Console output:
![image](https://user-images.githubusercontent.com/34734202/142728302-2fec97fa-28c0-40ce-9408-e6975dd82066.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser MS Edge
 - Version 95.0.1020.53 (Official build) (64-bit)

**Additional context**
Rename below file from txt to py, before running it.
[unet_2015.txt](https://github.com/TylerYep/torchinfo/files/7574616/unet_2015.txt)

**Comment by TylerYep** [comment]
You need to pass the dtype to torchinfo. See the readme docs for details :)
