### ISSUE TITLE
summary function changes the device of the network

### ISSUE THREAD

**Issue by MSutharsan** [TylerYep/torchinfo#106]
I use GPU 1 for the device and the data.  When I call the summary in the middle, the device of the network changes to GPU 1 and makes conflicts while training. Please check this issue

**Comment by TylerYep** [comment]
I think you want to look at the `device` parameter in the documentation:
```
 device (torch.Device):
            Uses this torch device for model and input_data.
            If not specified, uses result of torch.cuda.is_available().
            Default: None
```

**Comment by MSutharsan** [comment]
Thank you. It works
