### ISSUE TITLE
Official Citation Needed

### ISSUE THREAD

**Issue by YimingMa** [TylerYep/torchinfo#110]
**Is your feature request related to a problem? Please describe.**

Hi dear developers. I am using your package and would like to cite it in papers. Could you provide with your official citation style in  bibtex? Many thanks, Yiming.

**Describe the solution you'd like**
Citation in bibtex.

**Describe alternatives you've considered**

**Additional context**

**Comment by TylerYep** [comment]
I generated a CITATIONS.cff file so that you can click `Cite this repository` on the main page. In BibTex:
```
@software{Yep_torchinfo_2020,
    author = {Yep, Tyler},
    license = {MIT},
    month = {3},
    title = {{TorchInfo}},
    url = {https://github.com/TylerYep/torchinfo},
    year = {2020}
}
```
