### ISSUE TITLE
Docs on `nn`

### ISSUE THREAD

**Issue by OverLordGoldDragon** [TylerYep/torchinfo#111]
I think it's important to document that all ops should be done via `nn`, else they won't be tracked (in memory and flops). E.g. `x.mean` is invisible, as opposed to `AvgPool1d` (though its flops and memory still aren't tracked). Would also help to detect if there are non-`nn` ops, or non-contributing layers like `AvgPool1d` and warn the user of potential inaccuracies (or document it).

That said, is there a way to ensure correctness for things like `x = x + 1`? Wrapping `torch.add` in `nn.Module` doesn't do it.

**Comment by TylerYep** [comment]
Totally agree, a lot of operations are not supported but definitely could in the future. I'll add this to the documentation.

Note that torchinfo is built around supplementing information of print(model) in Pytorch, so it is unlikely we will list "add" operations and other non-layer operations.

**Comment by OverLordGoldDragon** [comment]
Thanks

`AvgPool1d` falls under `print(model)`, so is its support planned? Such layers create lots of intermediate tensors which matter for memory more than flops; I often find the "total memory" disagreeing greatly with Task Manager, maybe because of this. It should be possible to track these via hooks

**Comment by TylerYep** [comment]
Yep, AvgPool and MaxPool are definitely on the todo list. PRs adding support for these are greatly appreciated!

**Comment by TylerYep** [comment]
@OverLordGoldDragon Could you provide a simple example model for AvgPool1d? I will add a test case and investigate why it's not showing up. MaxPool2d seems to work fine, so not sure what the differences are

**Comment by TylerYep** [comment]
I believe AvgPool1d is now tracked in torchinfo in recent releases. Feel free to reopen if you find this is not the case.
