### ISSUE TITLE
View if requires_grad is true

### ISSUE THREAD

**Issue by bsridatta** [TylerYep/torchinfo#115]
It would be pretty helpful to see what layers are frozen and what are not. There is already an indication of how many params are trainable and what is not, but also viewing per layer setting would be useful. Thanks!

**Comment by TylerYep** [comment]
Thanks for the suggestion! This sounds like a pretty good first contribution if anyone is interested:
- Add a new col_name
- in the constructor of LayerInfo, set a new attribute is_trainable
- Add this to the output and add a test case

**Comment by bsridatta** [comment]
I could give it a shot!

**Comment by TylerYep** [comment]
Implemented in #128 and will be released in v1.6.6
