### ISSUE TITLE
Specify torch dependency version

### ISSUE THREAD

**Issue by xuyangt3** [TylerYep/torchinfo#123]
The newset release 1.6.4 uses torch.nn.parameter.is_lazy, which does not exist until torch version 1.9 and it doesn't show up in the docs. As a result, I am getting this error:

![image](https://user-images.githubusercontent.com/42992447/160136191-f2179112-7358-4f68-a5fd-7048755a9915.png)

**Comment by TylerYep** [comment]
Oops, this is a regression. Let me push out a new release fixing this.

**Comment by TylerYep** [comment]
This has been fixed in v1.6.5
