### ISSUE TITLE
Question: MixedTrainableParameters model used in test does not include bias in forward pass

### ISSUE THREAD

**Issue by bsridatta** [TylerYep/torchinfo#127]
Since the info is extracted with some hook, should the bias also be part of the forward pass?

https://github.com/TylerYep/torchinfo/blob/ea0d1f73c3747fe134b668e895337b94c53f44c5/tests/fixtures/models.py#L493-L502

**Comment by TylerYep** [comment]
Sure, I'll add this for completeness. It doesn't affect the torchinfo output though, since all parameter info is obtained before the forward pass.

**Comment by bsridatta** [comment]
I see, thanks for the clarification!
