### ISSUE TITLE
Model summary for geometric inputs?

### ISSUE THREAD

**Issue by daniCh8** [TylerYep/torchinfo#131]
Hey guys,

I am a big fan of your work. Lately, I have been working with 3D data and using [`torch_geometric Data`](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.Data) as input. This type is not currently supported in the possible `INPUT_DATA_TYPES` in the summary method. I am not sure how hard would it be to do it, but it would be great if you could add this feature.

To try this out, you could use a model from [`torch_points3d.applications`](https://github.com/torch-points3d/torch-points3d) (code below). In my mind, this could work by passing a random [`Data`](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.Data) or [`Batch`](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.Batch) object as `input_data` in the `summary` method, like this:

```python
import torch
from torch_points3d.applications.pointnet2 import PointNet2
from torch_geometric.data import Batch, Data
from torchinfo import summary

num_points = 1024
out_num_classes = 10
input_num_classes = 5

pos = torch.randn((num_points, 3)).unsqueeze(0)
T = torch.randn((num_points, input_num_classes)).unsqueeze(0)

data = Data(pos=pos, x=T)
data = Batch.from_data_list([data, data])

model = PointNet2(architecture="unet", input_nc=input_nc, num_layers=3, output_nc=out_num_classes)
summary(model, input_data=data)
```

Thanks in advance!

**Comment by TylerYep** [comment]
Hi, passing in generic inputs is currently supported via kwargs arguments to summary() e.g.

```
# replace data= with whatever the variable name the forward() function uses
summary(model, data=data)
```

This should at the very least print a high-level summary.

I don't see a general way of supporting or getting additional layer info from custom structs, so this will likely be the best that torchinfo will be able to support. Investigatory PRs are always welcome though!

**Comment by daniCh8** [comment]
Hi, thank you for your quick reply! I didn't know about the possibility of passing in generic inputs. You are right; the summary I get doing so is high-level, but it's enough as far as I'm concerned. I'm closing this issue.
