### ISSUE TITLE
hrnetv2  summary  assert mod is not None

### ISSUE THREAD

**Issue by kk125678** [TylerYep/torchinfo#135]
i use hrnetv2 in  mmseg,it has None  in submodule . it causes assert in summary  line 576
![image](https://user-images.githubusercontent.com/46900538/165281894-211218a3-1e53-4ef1-8818-be016987c9c5.png)
i think maybe change assert to if mod is not None

**Comment by kk125678** [comment]
pip install mmcv-full 
pip install mmsegmentation
pip install torchinfo

from mmseg.models.backbones.hrnet import HRNet
import torch
from torchinfo import summary
extra = dict(
             stage1=dict(
                 num_modules=1,
                 num_branches=1,
                 block='BOTTLENECK',
                 num_blocks=(4, ),
                 num_channels=(64, )),
             stage2=dict(
                 num_modules=1,
                 num_branches=2,
                 block='BASIC',
                 num_blocks=(4, 4),
                 num_channels=(32, 64)),
             stage3=dict(
                 num_modules=4,
                 num_branches=3,
                 block='BASIC',
                 num_blocks=(4, 4, 4),
                 num_channels=(32, 64, 128)),
             stage4=dict(
                 num_modules=3,
                 num_branches=4,
                 block='BASIC',
                 num_blocks=(4, 4, 4, 4),
                 num_channels=(32, 64, 128, 256)))
hr48 = HRNet(extra=ext,norm_cfg = dict(type='SyncBN', requires_grad=True))
#print(hr48)
summary(hr48, input_size=(1, 3, 512, 512))

**Comment by kk125678** [comment]
In mmseg.models.backbones.hrnet line 485
 transition_layers.append(None)
'None' is insert to model

**Comment by TylerYep** [comment]
Fixed in e7be90b and will be in release v1.6.6. Thank you for reporting this issue!
