### ISSUE TITLE
AttributeError: 'list' object has no attribute 'size'

### ISSUE THREAD

**Issue by roboserg** [TylerYep/torchinfo#139]
![image](https://user-images.githubusercontent.com/4758917/168480439-eda81859-41cf-4ae9-a231-561bd9266763.png)

Maybe I supply the wrong input_size? My model:

![image](https://user-images.githubusercontent.com/4758917/168480462-d8186566-7146-4ad2-a9ad-e07c29e202ab.png)

**Comment by roboserg** [comment]
I also tried using the batch_size:

![image](https://user-images.githubusercontent.com/4758917/168480537-7a20532c-9fe9-481b-9c05-8b12acf410fa.png)

**Comment by TylerYep** [comment]
Can you post your full model code? Your model likely accepts a list instead of a tensor as input. Try using the `input_data` param instead with your actual input data tensor for better results.

**Comment by roboserg** [comment]
Here you go - https://colab.research.google.com/drive/1wF3XyaN_WL7mR0qmWj6w7--pCC6TCYUF?usp=sharing

I changed the model to YOLOX and now getting a different error - 
![image](https://user-images.githubusercontent.com/4758917/168680506-9cf96124-178d-4a33-8cd2-21324ce9602f.png)

Is there a way to not supply input size at all? In Keras the summary is printed automatically, without figuring out the input size

**Comment by TylerYep** [comment]
Yes, you can just not pass the input_size parameter and get some limited results.

If your forward function needs additional parameters, you should pass them as kwargs:

`summary(model, input_size=(3, 512, 512), img_metas=...)`

**Comment by TylerYep** [comment]
Closed due to inactivity
