### ISSUE TITLE
Output shape of the input layer

### ISSUE THREAD

**Issue by X-Chen97** [TylerYep/torchinfo#146]
Why is the output shape of the input layer (first line) [32, 1]? Shouldn't it be [32, 10]?

<img width="1216" alt="CleanShot 2022-06-14 at 17 09 29@2x" src="https://user-images.githubusercontent.com/54193597/173710135-22d28f5c-ef5f-4096-9d1f-7d5928379049.png">

**Comment by TylerYep** [comment]
The first line is the overall model input/output.

**Comment by X-Chen97** [comment]
Got it. Thought it was the shape of the input layer.
