### ISSUE TITLE
A cpu version pytorch needs to be installed when installing torchinfo with Conda

### ISSUE THREAD

**Issue by 1ofsomepeople** [TylerYep/torchinfo#155]
**Describe the bug**
When I try to install torchinfo with Conda, the recommend command "conda install -c conda-forge torchinfo" want to install a CPU version pytorch, but I have installed a GPU version pytorch. I didn't notice that the first time, and It makes my GPU version pytorch is unavailiable.

**Expected behavior**
Can I use torchinfo with GPU version Pytorch the same time? 

**Screenshots**

![issue](https://user-images.githubusercontent.com/54463858/181251423-08e5d6eb-407a-4006-a865-e84dd659c229.png)

**Comment by TylerYep** [comment]
You should install the GPU version of pytorch first, and then when you install torchinfo after it will realize the dependency is already satisfied.

**Comment by 1ofsomepeople** [comment]
Thanks for help. I found the GPU version of Pytorch is installed by **pip**, which cann't be mannaged by conda, so i reinstalled a GPU version of Pytorch by conda, and it works.
