### ISSUE TITLE
Idea: add the column "Params %" in addition to "Params #"

### ISSUE THREAD

**Issue by Yura52** [TylerYep/torchinfo#159]
I use `torchinfo` to get a rough understanding of model sizes and how the "weight" is distributed across the model. Unfortunately, the latter information is not available directly, which is not convenient, especially with larger models. So I suggest adding one more column which contains the ratio `n_params / total_n_params`. It would immediately provide new important insights almost for free.

**Comment by TylerYep** [comment]
This is a good idea! PRs adding this functionality are welcome (the functionality should be fairly straightforward)
