### ISSUE TITLE
CUDA error: Out of memory 

### ISSUE THREAD

**Issue by bsridatta** [TylerYep/torchinfo#197]
Inference code crashes with CUDA out of memory error at torchinfo `summary()`. This is happened on an already working script with summary() unclear what has changed,

Commenting the summary() line fixed it. And I couldnt not notice the memory exceeding 20% when this error pops. This is definitely something to with the machine but any pointer to know why it only impacts torchinfo would be helpful. Thank you!

```
   summary(model, input_size=[1] + model.input_modules["image"])  # Dummy batchsize, 1.

  File "/home/dattab/.local/share/virtualenvs/seat_belt_detection-M8EBEog7/lib/python3.8/site-packages/torchinfo/torchinfo.py", line 214, in summary
    x, correct_input_size = process_input(
  File "/home/dattab/.local/share/virtualenvs/seat_belt_detection-M8EBEog7/lib/python3.8/site-packages/torchinfo/torchinfo.py", line 249, in process_input
    x = get_input_tensor(correct_input_size, batch_dim, dtypes, device)
  File "/home/dattab/.local/share/virtualenvs/seat_belt_detection-M8EBEog7/lib/python3.8/site-packages/torchinfo/torchinfo.py", line 485, in get_input_tensor
    x.append(input_tensor.to(device).type(dtype))
RuntimeError: CUDA error: out of memory
```

**Comment by mert-kurttutan** [comment]
Running summary on torchinfo also occupies some memory. It does only forward prop
I think a better question would be what is the memory consumption due to summary? Is it as high as expected?
Maybe you could show nvidia-smi before and after this line to get the memory consumption of summary.

**Comment by bsridatta** [comment]
Thanks for the response @mert-kurttutan !

Yes, thats true and thats why its weird. Memory consumption due to summary seems negligable. 

I ran the script in debug mode, check gpu stats, run `summary(model, input_size=[1] + model.input_modules["image"])  # Dummy batchsize, 1.` in debug console, throws out of memory error, the gpu stats is the same. Same observation running it normally with out debug.

before-
![Pasted image 20221116125324](https://user-images.githubusercontent.com/17333185/202174057-5d9f01f9-b445-4336-aba4-88dc19747954.png)
after-
![image](https://user-images.githubusercontent.com/17333185/202174366-c276c664-80fd-4afc-a7e8-1615b1439697.png)

**Comment by mert-kurttutan** [comment]
wow that is really weird. 
Could you provide the definition of the model?

**Comment by bsridatta** [comment]
Its a mobilenetv2 with quant layers. But it worked fine for the past 5 months. I think its my environment thats the issue (I am experiencing other problems as well). So I shall close this one and update here if I discover the reason. 

Thanks for your time and inputs
