### ISSUE TITLE
Cannot assign str/repr from model.summary to a variable without 'workaround' in Colab

### ISSUE THREAD

**Issue by Antsthebul** [TylerYep/torchinfo#218]
Not sure if this should be a feature request since a solution is known...

**Describe the bug**

According to [Py-pi/torch-summary](https://pypi.org/project/torch-summary/):

> from torchsummary import summary
model_stats = summary(your_model, (3, 28, 28), verbose=0)
summary_str = str(model_stats)

And while also keeping in mind what was mentioned  on GitHub
>Note: if you are using a Jupyter Notebook or Google Colab, summary(model, ...) must be the returned value of the cell. If it is not, you should wrap the summary in a print(), e.g. print(summary(model, ...)). See tests/jupyter_test.ipynb for examples.

I was unable to assign the str of `summary` to a value and using going colab the `print` statement is not required for the cell to display the results

**To Reproduce**
1. Create a model in google colab and install necessary libraries
2. Try to create a variable using `str` wrapper around `summary`, varibale will not be returned

**Expected behavior**

**Screenshots**

# screenshot 1
*Colab Cell repr (also value not assigned)*
![image](https://user-images.githubusercontent.com/56587872/215360559-7be01077-1a0a-4f07-af46-aa2c1e623f03.png)

# screenshot 2
*Colab cell (w/str)*
![image](https://user-images.githubusercontent.com/56587872/215360595-d22e14e0-d8da-4eaf-80fb-17a42630943f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
# screenshot 3
Solution is to use contextlib **Note:** *print statement used to evaluate newlines*. 

![image](https://user-images.githubusercontent.com/56587872/215360634-b6f8cbcb-24a0-4f19-ad1e-fa8d322a53e7.png)

**Comment by Antsthebul** [comment]
@snimu so sorry. I didnt mean to waste your time, but I apprecaite your response. It appears that alought the import  is the same `from torchsummary [..]` there are 2 different packages. I've been using the `pytorch-summary` pkg, and not `torch-summary`

**Comment by snimu** [comment]
@Antsthebul no problem :) I'm glad that I could help.

**Comment by TylerYep** [comment]
@Antsthebul  Please use `torchinfo` instead of `torch-summary`, thanks!
