### ISSUE TITLE
bug when an axis=-1

### ISSUE THREAD

**Issue by hanochk** [TylerYep/torchinfo#22]
https://github.com/TylerYep/torchinfo/blob/2c94c1425b96f749951c6e3a857365932c9067af/torchinfo/model_statistics.py#L46

prod can be < 0 in case dimention is [-1, 32, 128, 128]
hence replace with np.abs(prod())

**Comment by TylerYep** [comment]
Hmm... I don't quite see the issue. prod is defined as:
```
def prod(num_list: Union[Iterable[Any], torch.Size]) -> int:
    result = 1
    for num in num_list:
        result *= num
    return abs(result)
```
which takes the absolute value, so prod is always >= 0.

**Comment by hanochk** [comment]
Running it under debug mode keep the minus sign. Plus why abs is used over
the final result later on in the code as if trying to resolve that ?

**Comment by hanochk** [comment]
Maybe we have different python versions. I'll check it out tomorrow.

**Comment by TylerYep** [comment]
Maybe check to see if you have the latest version of torchinfo/torch-summary? There is only one `abs()` function call in the entire codebase at the moment.
