### ISSUE TITLE
Mebabytes and Megabibytes are different 

### ISSUE THREAD

**Issue by kartik4949** [TylerYep/torchinfo#23]
1 MB (megabyte) = 1000000 bytes
1 MiB (Megabibyte) = 1024 * 1024 bytes

either change  / 1024 ** 2 to * 1e-6 
or change  MB to MiB
one for my colleague in popular project helped me point out this issue. :)

**Comment by TylerYep** [comment]
Wow, thank you for pointing this out! I never knew there was a difference. You should be able to see the updated values in the new release tomorrow.

**Comment by kartik4949** [comment]
@TylerYep will file a pr. may be :) got more changes in mind.

**Comment by TylerYep** [comment]
I pushed the change to 1e6 and fixed all the test cases just now, please pull latest master!

**Comment by kartik4949** [comment]
Sure :)
