### ISSUE TITLE
pytorch2.0 warning

### ISSUE THREAD

**Issue by YoRHazzz** [TylerYep/torchinfo#238]
I got this warning:
"UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage() 
 action_fn=lambda data: sys.getsizeof(data.storage())"
and this warning:
"UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return super().__sizeof__() + self.nbytes()"
while working with pytorch2.0

**Comment by TylerYep** [comment]
This has been fixed in `7f2bed3` and will be released in v1.8.0.
