### ISSUE TITLE
TypedStorage is deprecated

### ISSUE THREAD

**Issue by joaolcguerreiro** [TylerYep/torchinfo#245]
Hi everytime you run summary() a UserWarning pops up.

This is a warning message that is telling you that the use of TypedStorage in your code is deprecated and will be removed in the future. Instead, you should use UntypedStorage, which will be the only storage class available.

To access UntypedStorage directly, you should use the method untyped_storage() instead of storage().

It is recommended to update your code to use UntypedStorage instead of TypedStorage to avoid any issues in the future when TypedStorage is removed.

**Comment by TylerYep** [comment]
This was already fixed in https://github.com/TylerYep/torchinfo/commit/7f2bed35319496796b9e6448beadcf7d420e79ab
and will be included in v1.7.3. Thanks!
