### ISSUE TITLE
doesn't work with parameters in a parameterlist

### ISSUE THREAD

**Issue by lizardzandwizardz** [TylerYep/torchinfo#28]
As the title says. torchinfo cannot determine the size of the weights in a parameterlist, and therefore it doesn't calculate the size of the network properly. 
Fix would be greatly appreciated! torchinfo is amazing! 

example: 
```
import torch
import torchinfo

class Test(torch.nn.Module):
    def __init__(self):
        super(Test, self).__init__()
        weight = torch.Tensor(100, 300)
        weights = weight.split([100, 200], dim=1)
        weights = [torch.nn.Parameter(weight) for weight in weights]
        self.weights = torch.nn.ParameterList(weights)
    
    def forward(self, x)
        return x

model = Test()
input_shape = (100,100)
torchinfo.summary(model, [input_shape], batch_dim=None, device='cpu', dtypes=[torch.float32], depth=7, verbose=2)
```

**Comment by TylerYep** [comment]
Can you clarify what you expect the output to be? I think torchinfo isn't printing anything because you are not using the weights in your forward() function.

Adding this feature might require a bigger overhaul of the library, we'll see.

**Comment by lizardzandwizardz** [comment]
I'd like torchinfo to print the total size of the model accurately. With all its parameters and buffers included. 

Right now, i could have a model with so large parameters, that i can't upload it to the device, but torchinfo will say its size is 1 MB. 

It's a problem for me, because I'm experimenting with custom embedding layers. I'd like to see how large the whole model is. 

Can't we just recursively iterate over the parameters and buffers of the model, and use numel() or nelement()? 

Maybe it's possible to get memory consumption from pytorch allocator. Idk.

**Comment by lizardzandwizardz** [comment]
The size estimation of the forward / backward pass seems to be fine. The size of the parameters doesn't include parameterlists. Even when i use those tensors. (as embeddings)

**Comment by lizardzandwizardz** [comment]
Help is greatly appreciated!

**Comment by lizardzandwizardz** [comment]
a.element_size() * a.nelement()
would be the size of tensor a in bytes

**Comment by lizardzandwizardz** [comment]
I can see in model_statistics.py L81 that floats are assumed everywhere. In mixed precision training training some weights are in fp16 or tf16 (truncated float).

**Comment by TylerYep** [comment]
> I can see in model_statistics.py L81 that floats are assumed everywhere. In mixed precision training training some weights are in fp16 or tf16 (truncated float).

You probably want to open a separate issue for this!

**Comment by TylerYep** [comment]
This should be working now! Fixed in https://github.com/TylerYep/torchinfo/commit/1737da35bb1b69bd18b2c180d6d54f367fd0de9c
