### ISSUE TITLE
size estimation of model assumes floats everywhere

### ISSUE THREAD

**Issue by lizardzandwizardz** [TylerYep/torchinfo#29]
I can see in model_statistics.py L81 that floats are assumed everywhere. In mixed precision some weights are in fp16 or tf16 (truncated float). Quantized models use int8 weights and a separate float as parameter. 
The estimated size of the model should be correct, and it should depend on what model we hand over to summary(...).

**Comment by lizardzandwizardz** [comment]
for example, when i call
model = model.half()
before calling summary, i expect the size estimate to be half as large as before. 
(assuming, i used summary on a model with float32 weights).

**Comment by lizardzandwizardz** [comment]
it's important, because tensorcores are made for fp16 calculations, and so inference is a lot faster when done in fp16
when the size of the model is smaller, we can use a larger batch_size for inference
knowing how large that is would be great

**Comment by TylerYep** [comment]
That makes sense, I would appreciate a PR to fix this if you can!

**Comment by MajorCarrot** [comment]
I'll try and work on this (if possible) this week. I am using torchinfo in one of my projects (evaluation of different pruned and quantized networks in one-shot setting) and this would be pretty handy

**Comment by MajorCarrot** [comment]
Update on this (sorry for the extremely late reply), I found some documentation on [dtypes used by pytorch](https://pytorch.org/docs/stable/tensors.html#data-types) at which can help find the datatype of the current weights (difficult to implement but might be possible). This can be queried using the [Tensor.type](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html#torch.Tensor.type) function

There is also an [attribute](https://pytorch.org/docs/master/generated/torch.Tensor.is_quantized.html#torch-tensor-is-quantized) which can be used to find if the tensor is quantized!

**Comment by jedi2610** [comment]
@TylerYep i think i might have a solution here, but i'm not sure tho. this is what i have in mind:

1. in [L142](https://github.com/TylerYep/torchinfo/blob/main/torchinfo/layer_info.py#L142) of `layer_info.py`, you can prolly do something like:
```python
self.param_size += param.element_size() * param.nelement()
```
2. in [L31](https://github.com/TylerYep/torchinfo/blob/main/torchinfo/model_statistics.py#L31) of `model_statistics.py`, something like:
```python
self.total_param_size += layer_info.param_size
```
and refactor `__repr__` correspondingly.

we can do this similarly for the forward/backward pass size in [L508](https://github.com/TylerYep/torchinfo/blob/5a4be28da7e36f887dcb4cdd744a33800fd16321/torchinfo/torchinfo.py#L508) of `torchinfo.py`.

i am willing to contribute, so i also tried to see if it works in a simple model.
i tested it on the `LSTMNet()` model from README and it does work after doing `model.half()`.

this obviously needs more testing than this and i don't know if this would work for all models. i also don't know if it would work when used in mixed precision. but i wanted to know if i am heading in the right direction tho. what do you think? ty

reference:
1. https://discuss.pytorch.org/t/how-to-know-the-memory-allocated-for-a-tensor-on-gpu/28537

**Comment by TylerYep** [comment]
This sounds like a good solution (at least as a first attempt). If it passes all of the test cases as well as the new half() test cases I'm willing to accept a PR!

**Comment by jedi2610** [comment]
okay cool i'll fork this project and let you know on the progress later tomorrow.

**Comment by TylerYep** [comment]
A first pass support for half-precision models has been added in #109 . If there are any issues, feel free to re-open this.

Thank you to @jedi2610 for completing this feature!
