### ISSUE TITLE
Recursion cannot stop when using summary for combined model

### ISSUE THREAD

**Issue by Rundong-Li** [TylerYep/torchinfo#33]
I defined a Seq2seq model using two model (encoder and decoder) and instantiated them like this
```python
enc = model.Encoder(...)
dec = model.Decoder(...)
seq2seq = model.Seq2Seq(enc, dec, device).to(device)
```
then I found
```python
summary(enc, [(config.MAX_SENTENCE_SIZE, config.BATCH_SIZE), (config.MAX_SENTENCE_SIZE, config.BATCH_SIZE)], dtypes=[torch.LongTensor, torch.LongTensor])
```
will print the summary of parameters but the recursion cannot stop, like this:
![endless recursion](https://user-images.githubusercontent.com/48337831/113542105-2179a800-9616-11eb-9930-14773a08aedb.png)
If I seperately call ```summary(enc)``` and ```summary(dec)```, it works fine
![屏幕截图 2021-04-05 135510](https://user-images.githubusercontent.com/48337831/113542320-96e57880-9616-11eb-83b9-e6db85d76937.png)
I wonder if there's any solution to it, or ```summary``` can only apply to combined models built like the example in [Sequentials & ModuleLists](https://github.com/TylerYep/torchinfo#sequentials--modulelists) using ```nn.ModuleList()```

**Comment by TylerYep** [comment]
Hmm yes this looks like an issue. Does the program terminate, or does it loop infinitely?

**Comment by Rundong-Li** [comment]
> Does the program terminate, or does it loop infinitely?
> 
> If it terminates, then this is probably not fixable, since arguably this is an accurate summary of the model. Perhaps I can truncate the output, but I don't really want to maintain a separate output for these types of cases.

It terminates. 
Thanks for your reply. I think seperately using ```summary(enc)``` and ```summary(dec)``` is fine.

**Comment by TylerYep** [comment]
Got it, thanks for letting me know! I can add a note in the README explaining this behavior.
