### ISSUE TITLE
total MACs error caused by sum with MACs of non leaf layer

### ISSUE THREAD

**Issue by zmzhang2000** [TylerYep/torchinfo#39]
When I compute the total mult-adds of ResNet18, the result is quite different with the [original paper](https://arxiv.org/abs/1512.03385) (11.71G vs. 1.8G).

After inspection, I found the torchinfo result is the sum of MACs of all layers. However, I think the MACs of a model should be the sum of leaf layers.

For example, if there is a Sequential module
```python
self.convs = nn.Sequential(
    nn.Conv2d(in_channels=16, out_channels=16, kernel_size=3),
    nn.Conv2d(in_channels=16, out_channels=16, kernel_size=3),
    nn.Conv2d(in_channels=16, out_channels=16, kernel_size=3),
)
```
torchinfo will sum the MACs of [Sequential(self.convs), Conv2d(0), Conv2d(1), Conv2d(2)] rather than [Conv2d(0), Conv2d(1), Conv2d(2)]. 

Besides, the MACs computation of non leaf layers is wrong with current method calculate_macs(), which could be different with sum of sub-layer MACs:
```python
for name, param in self.module.named_parameters():
    if name == "weight":
        # ignore C when calculating Mult-Adds in ConvNd
        if "Conv" in self.class_name:
            self.macs += int(
                param.nelement()
                * prod(self.output_size[:1] + self.output_size[2:])
            )
        else:
            self.macs += self.output_size[0] * param.nelement()
    # RNN modules have inner weights such as weight_ih_l0
    elif "weight" in name:
        self.macs += prod(self.output_size[:2]) * param.nelement()
```

The problem is inconspicuous, as the output MACs of non leaf layers is "--". You could find the problem by sum the output MACs of each leaf layer, which is quite different with the output total MACs.

I will create a PR if the finding is a real problem.

**Comment by TylerYep** [comment]
Thanks for finding this, the MACs calculation was inherited from a different codebase and possibly has several bugs. I would appreciate any PRs to improve this functionality!

We should also definitely add test cases to confirm these calculations are correct for all future versions of torchinfo!

**Comment by zmzhang2000** [comment]
Thank you. I have created a PR #40 to fix. Waiting for your review!

**Comment by zmzhang2000** [comment]
> Thanks for finding this, the MACs calculation was inherited from a different codebase and possibly has several bugs. I would appreciate any PRs to improve this functionality!
> 
> We should also definitely add test cases to confirm these calculations are correct for all future versions of torchinfo!

Thank you. I have created a PR #40 to fix. Waiting for your review!
