### ISSUE TITLE
No verbose option

### ISSUE THREAD

**Issue by InCogNiTo124** [TylerYep/torchinfo#41]
`summary(model, input_size, verbose=2, device='cpu')` returns

`TypeError: summary() got an unexpected keyword argument 'verbose'`

**Comment by InCogNiTo124** [comment]
Solved by installing from source:

```
git clone https://github.com/TylerYep/torchinfo.git
cd torchinfo
python3 setup.py build
sudo -E python3 setup.py install
```

Interestingly enough, running `pip install --upgrade git+https://github.com/TylerYep/torchinfo.git` somehow installed an older version. Wonder what could've went wrong

**Comment by TylerYep** [comment]
Hmm I've never seen this issue before. You might have installed the wrong project by accident? If I recall correctly `verbose` has always been available in torchinfo...
