### ISSUE TITLE
Modules with non-tensor forward parameters

### ISSUE THREAD

**Issue by apivovarov** [TylerYep/torchinfo#44]
Some model designers use non-tensor forward parameters for internal model modules. (e.g. Detectron2)
- [proposal_generator.forward()](https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/proposal_generator/rpn.py#L431)
- [call of proposal_generator.forward()](https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/meta_arch/rcnn.py#L157) from top level module

What can be done to print the model summary in such case?
Example:
```
import torch
import torch.nn as nn
from torchinfo import summary

class MyImage:
    def __init__(self, tensor):
        self.tensor = tensor
    def __len__():
      return 1
    def __getitem__():
      return self.tensor

class Net2(nn.Module):
    def forward(self, m1, i1):
        return m1["tensor"] + i1.tensor

class Net1(nn.Module):
    def __init__(self, net2):
        super(Net1, self).__init__()
        self.net2 = net2
    def forward(self, x, y):
        m1 = dict()
        m1["tensor"] = x
        i1 = MyImage(y)
        res = self.net2(m1, i1)
        return res

net2 = Net2()
net = Net1(net2)
x=torch.ones(1,2,4,4)
y=torch.ones(1,2,4,4)
net(x, y)
print(net)
summary(net, input_data=[x,y], col_names=["input_size", "output_size"])
```

Current output does not have top Net1 layer.
```
==========================================================================================
Layer (type:depth-idx)                   Input Shape               Output Shape
==========================================================================================
├─Net2: 1-1                              []                        [1, 2, 4, 4]
==========================================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
Total mult-adds (M): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================
```

**Comment by TylerYep** [comment]
By default, torchinfo currently does not display the overall model name, which is why you aren't seeing Net1 at the moment. This is a bug, and I am working on fixing that issue.

Regarding the input/output: that is a tricky problem, since the only way we currently track input and output sizes is by treating all layers as (tensor -> tensor) functions. I'd appreciate any PRs here allowing or expanding this functionality!

**Comment by apivovarov** [comment]
Thank you for the info!
I also faced runtime error (out of boundary index) in [nested_list_size](https://github.com/TylerYep/torchinfo/blob/main/torchinfo/layer_info.py#L59).
It happens when `inputs` is empty tuple.

**Comment by TylerYep** [comment]
Fixed two of these errors in v0.1.1!

If you find ways to support non-tensor forward parameters, please feel free to support a PR. Otherwise, this functionality is currently out of scope for the time being. Thanks!

**Comment by apivovarov** [comment]
I got the following for my test model now. (Commit [41f7e91](https://github.com/TylerYep/torchinfo/commit/41f7e91e1a1155993f80cbd871cc781fdaf9725b))
```
==========================================================================================
Layer (type:depth-idx)                   Input Shape               Output Shape
==========================================================================================
Net1                                     --                        --
├─Net2: 1-1                              --                        [1, 2, 4, 4]
==========================================================================================
```

Well, `Net1` is "normal" Module. It has Tensor-type inputs (2 of them) and 1 output.
Is it possible to show their shape?

**Comment by apivovarov** [comment]
BTW, Can `.summary` show multiple input shapes in case when a module has more than 1 input parameters in forward()?
```
class Net(nn.Module):
    def forward(self, x, y):
        return x + y

x=torch.rand(1,2,4,4)
y=torch.ones(1,1,4,4)
net(x,y)
summary(net, input_data=[x,y], col_names=["input_size", "output_size"])
```
Now it shows just the first input shape
```
==========================================================================================
Layer (type:depth-idx)                   Input Shape               Output Shape
==========================================================================================
Net1                                     [1, 2, 4, 4]              [1, 2, 4, 4]
==========================================================================================
```

**Comment by TylerYep** [comment]
1. I'll consider making a change to show the overall model layer shapes, but it does make the summary table less easily readable, since the top row would show the overall model's (input -> output), while all other rows would show linear progression through the model layers.

2. It is not currently possible to show multiple input or output shapes. Both are planned features but it will take a lot of planning to ensure that the sizes show up clearly in the summary table - previous issues also requested supporting multiple tensors in a list or dict of inputs, and we currently only show the first tensor in that list/dict.
