### ISSUE TITLE
how to use torchinfo with model taking dictionary as input ?

### ISSUE THREAD

**Issue by TrungQuocNguyen** [TylerYep/torchinfo#46]
Hi, I think this question should be asked already, but I still cannot find any answer for it. I try to test my model which accepts a dictionary of Tensor as input, and want to use torchinfo for it. However, although I have tried many ways, the error still pops up
Number of things I try: 
summary(model, input_data = data) 
summary(model, input_data = [data])
summary(model, input_data = (data))
data is a dictionary to my model, which has function forward(data)
How can I use torchinfo with dictionary ?

**Comment by TylerYep** [comment]
Can you post the full error here? (it should be very long) The first one you gave should work.

**Comment by TrungQuocNguyen** [comment]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/trung/anaconda3/envs/rfdnet/lib/python3.6/site-packages/torchinfo/torchinfo.py in summary(model, input_size, input_data, batch_dim, col_names, col_width, depth, device, dtypes, row_settings, verbose, **kwargs)
    176                 elif isinstance(x, dict):
--> 177                     _ = model.to(device)(**x, **kwargs)
    178                 else:

/home/trung/anaconda3/envs/rfdnet/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(

/home/trung/anaconda3/envs/rfdnet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    158         if len(self.device_ids) == 1:
--> 159             return self.module(*inputs[0], **kwargs[0])
    160         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])

/home/trung/anaconda3/envs/rfdnet/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(

TypeError: forward() got an unexpected keyword argument 'point_clouds'
my input dictionary is something like data ={'point_clouds': Tensor, ...}. The forward function of my model is def forward(self, data, export_shape=False). The error said that the keyword argument 'point_clouds' does not exist in the forward function. I read the code of torchinfo a bit and it looks like the dictionary is unpacked when it is passed to the model

**Comment by TylerYep** [comment]
We unpack your dict because torchinfo's one input parameter (input_data) needs to contain the multiple inputs to the model's forward function.

To fix this, you could use either:
```
summary(model, input_data=[data])
summary(model, input_data={"data": data})
```

If both of these do not work, can you post the source code of your model and the data? I can add a test case explaining the correct behavior.

**Comment by napster-ai** [comment]
Hi, I am also trying to use torchinfo with an input dictionary into my model. I used this source code https://github.com/graspnet/graspnet-baseline

the model is defined in train.py
net = GraspNet(input_feature_dim=0, num_view=cfgs.num_view, num_angle=12, num_depth=4, cylinder_radius=0.05, hmin=-0.02, hmax_list=[0.01,0.02,0.03,0.04])

and the input is batch_data_label which is a {dict: 8} made up of 3 tensors and 5 lists.
I get the following error:
```

Traceback (most recent call last):
  File "/home/workpc/anaconda3/envs/snowgrasp/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-7aa6498c48ca>", line 1, in <module>
    model_states = summary(net, input_data=[batch_data_label])
  File "/home/workpc/anaconda3/envs/snowgrasp/lib/python3.8/site-packages/torchinfo/torchinfo.py", line 160, in summary
    x, correct_input_size = process_input_data(input_data, device)
  File "/home/workpc/anaconda3/envs/snowgrasp/lib/python3.8/site-packages/torchinfo/torchinfo.py", line 279, in process_input_data
    raise RuntimeError(
RuntimeError: Input type is not recognized. Please ensure input_data is valid.
For multiple inputs to the network, ensure input_data passed in is a sequence of tensors or a list of tuple sizes. If you are having trouble here, please submit a GitHub issue.
```

**Comment by TylerYep** [comment]
Thanks for the example! I will take a look when I get a chance.

If you want to speed up the investigation process, you can help by posting a minimum reproducible example (i.e. as few lines of code as possible demonstrating the issue).

**Comment by shoeffner** [comment]
I have the same issue with pre-trained sentence embeddings from [sentence-transformers](https://www.sbert.net/docs/pretrained_models.html#sentence-embedding-models).

They use a method `encode(...)` which takes a list of sentences and returns the embeddings, but essentially it does this (simplified):

```python
# tokenized is a dict {'input_ids': [[...]], 'attention_mask': [[...]]}
batch = model.tokenize(sentences)
# batch_to_device pushes the tensors to the GPU
batch = batch_to_device(batch, 'cuda')
embeddings = model.forward(batch)
```

The problem is that some `forward`-functions expect a dictionary (or even multiple ones, I haven't investigated deeper).

You whould be able to try this:
```python
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import batch_to_device
from torchinfo import summary

model = SentenceTransformer('paraphrase-mpnet-base-v2')
input_data = batch_to_device(model.tokenize(['Take the cup to the table']), 'cuda')

summary(model, input_data=input_data)
# TypeError: forward() got an unexpected keyword argument 'input_ids'

summary(model, input_data={'features': input_data})
# RuntimeError: Input type is not recognized. Please ensure input_data is valid.
```

To "fix" it, I changed torchinfo/torchinfo.py:183 as follows:

```diff
diff --git a/torchinfo/torchinfo.py b/torchinfo/torchinfo.py
index 0834cf5..56312d6 100644
--- a/torchinfo/torchinfo.py
+++ b/torchinfo/torchinfo.py
@@ -180,7 +180,10 @@ def summary(
                 if isinstance(x, (list, tuple)):
                     _ = model.to(device)(*x, **kwargs)
                 elif isinstance(x, dict):
-                    _ = model.to(device)(**x, **kwargs)
+                    try:
+                        _ = model.to(device)(**x, **kwargs)
+                    except TypeError:
+                        _ = model.to(device)(x, **kwargs)
                 else:
                     # Should not reach this point, since process_input_data ensures
                     # x is either a list, tuple, or dict
```

This works for `summary(model, input_data=input_data)` in this case (and it might work for @TrungQuocNguyen), though I don't know if it generalizes -- probably not.

```
==============================================================================================================
Layer (type:depth-idx)                                       Output Shape              Param #
==============================================================================================================
SentenceTransformer                                          --                        --
├─Transformer: 1-1                                           [1, 768]                  --
│    └─MPNetModel: 2-1                                       [1, 8, 768]               --
│    │    └─MPNetEmbeddings: 3-1                             [1, 8, 768]               23,841,024
│    │    └─MPNetEncoder: 3-2                                [1, 8, 768]               85,054,848
│    │    └─MPNetPooler: 3-3                                 [1, 768]                  590,592
├─Pooling: 1-2                                               [1, 768]                  --
==============================================================================================================
Total params: 109,486,464
Trainable params: 109,486,464
Non-trainable params: 0
Total mult-adds (M): 109.49
==============================================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 6.65
Params size (MB): 437.95
Estimated Total Size (MB): 444.59
==============================================================================================================
```

**Comment by TylerYep** [comment]
Hi everyone, I recently published version 1.5.2, which should resolve all of the issues passing in a dictionary as the input.

`input_data` accepts whatever arguments your forward() function takes, so you can pass them in using a list, or as a kwargs dictionary:
```
tensors = {...}
summary(model, input_data=[tensors, other_args, ...])
```

Please open a new issue if you run into any problems with the new version!

**Comment by ChlaegerIO** [comment]
This from [shoeffner](https://github.com/shoeffner) commented [on Jun 21, 2021](https://github.com/TylerYep/torchinfo/issues/46#issuecomment-864631086) also solved my current issue. 

> I have the same issue with pre-trained sentence embeddings from [sentence-transformers](https://www.sbert.net/docs/pretrained_models.html#sentence-embedding-models).
> 
> They use a method `encode(...)` which takes a list of sentences and returns the embeddings, but essentially it does this (simplified):
> 
> ```python
> # tokenized is a dict {'input_ids': [[...]], 'attention_mask': [[...]]}
> batch = model.tokenize(sentences)
> # batch_to_device pushes the tensors to the GPU
> batch = batch_to_device(batch, 'cuda')
> embeddings = model.forward(batch)
> ```
> 
> The problem is that some `forward`-functions expect a dictionary (or even multiple ones, I haven't investigated deeper).
> 
> You should be able to try this:
> 
> ```python
> from sentence_transformers import SentenceTransformer
> from sentence_transformers.util import batch_to_device
> from torchinfo import summary
> 
> model = SentenceTransformer('paraphrase-mpnet-base-v2')
> input_data = batch_to_device(model.tokenize(['Take the cup to the table']), 'cuda')
> 
> summary(model, input_data=input_data)
> # TypeError: forward() got an unexpected keyword argument 'input_ids'
> 
> summary(model, input_data={'features': input_data})
> # RuntimeError: Input type is not recognized. Please ensure input_data is valid.
> ```
> 
> To "fix" it, I changed torchinfo/torchinfo.py:183 as follows:
> 
> ```diff
> diff --git a/torchinfo/torchinfo.py b/torchinfo/torchinfo.py
> index 0834cf5..56312d6 100644
> --- a/torchinfo/torchinfo.py
> +++ b/torchinfo/torchinfo.py
> @@ -180,7 +180,10 @@ def summary(
>                  if isinstance(x, (list, tuple)):
>                      _ = model.to(device)(*x, **kwargs)
>                  elif isinstance(x, dict):
> -                    _ = model.to(device)(**x, **kwargs)
> +                    try:
> +                        _ = model.to(device)(**x, **kwargs)
> +                    except TypeError:
> +                        _ = model.to(device)(x, **kwargs)
>                  else:
>                      # Should not reach this point, since process_input_data ensures
>                      # x is either a list, tuple, or dict
> ```
> 
> This works for `summary(model, input_data=input_data)` in this case (and it might work for @TrungQuocNguyen), though I don't know if it generalizes -- probably not.
> 
> ```
> ==============================================================================================================
> Layer (type:depth-idx)                                       Output Shape              Param #
> ==============================================================================================================
> SentenceTransformer                                          --                        --
> ├─Transformer: 1-1                                           [1, 768]                  --
> │    └─MPNetModel: 2-1                                       [1, 8, 768]               --
> │    │    └─MPNetEmbeddings: 3-1                             [1, 8, 768]               23,841,024
> │    │    └─MPNetEncoder: 3-2                                [1, 8, 768]               85,054,848
> │    │    └─MPNetPooler: 3-3                                 [1, 768]                  590,592
> ├─Pooling: 1-2                                               [1, 768]                  --
> ==============================================================================================================
> Total params: 109,486,464
> Trainable params: 109,486,464
> Non-trainable params: 0
> Total mult-adds (M): 109.49
> ==============================================================================================================
> Input size (MB): 0.00
> Forward/backward pass size (MB): 6.65
> Params size (MB): 437.95
> Estimated Total Size (MB): 444.59
> ==============================================================================================================
> ```
> 
> edit: Also, since the `forward`-function expects a dict, it is also not easily possible to pass in an input_size – but that's fine I guess.

**Comment by dyhan316** [comment]
It seems that when I want to pass a list of dict as one of the inputs (like below) I get an error. But the thing is, my model is only meant to work in this case. 

```
summary(model,  input_data={"x": inputs, "data_info_list" : data_info_list, "use_mask": False}, depth=4, verbose = 1)
```
where the data_info_list is a list of dicts like below
```
[{'Dataset': 'TUEG', 'modality': 'EEG', 'release': None, 'subject_id': 'aaaaaddm', 'task': None, 'sampling_rate': 500, 'segment_index': 41, 'start_time': 1230, 'channel_names': ['EEG FP1-REF', 'EEG FP2-REF', 'EEG F3-REF', 'EEG F4-REF', 'EEG C3-REF', 'EEG C4-REF', 'EEG P3-REF', 'EEG P4-REF', 'EEG O1-REF', 'EEG O2-REF', 'EEG F7-REF', 'EEG F8-REF', 'EEG T3-REF', 'EEG T4-REF', 'EEG T5-REF', 'EEG T6-REF', 'EEG FZ-REF', 'EEG CZ-REF', 'EEG PZ-REF'], 'xyz_id': array([[ -29.4367,   83.9171,   -6.99  ],
       [  29.8723,   84.8959,   -7.08  ],
       [ -50.2438,   53.1112,   42.192 ],
       [  51.8362,   54.3048,   40.814 ],
       [ -65.3581,  -11.6317,   64.358 ],
       [  67.1179,  -10.9003,   63.58  ],
       [ -53.0073,  -78.7878,   55.94  ],
       [  55.6667,  -78.5602,   56.561 ],
       [ -29.4134, -112.449 ,    8.839 ],
       [  29.8426, -112.156 ,    8.8   ],
       [ -70.2629,   42.4743,  -11.42  ],
       [  73.0431,   44.4217,  -12.    ],
       [ -84.1611,  -16.0187,   -9.346 ],
       [  85.0799,  -15.0203,   -9.49  ],
       [ -72.4343,  -73.4527,   -2.487 ],
       [  73.0557,  -73.0683,   -2.54  ],
       [   0.3122,   58.512 ,   66.462 ],
       [   0.4009,   -9.167 ,  100.244 ],
       [   0.3247,  -81.115 ,   82.615 ]])},

{'Dataset': 'TUEG', 'modality': 'EEG', 'release': None, 'subject_id': 'aaaaavzi', 'task': None, 'sampling_rate': 500, 'segment_index': 270, 'start_time': 8100, 'channel_names': ['EEG FP1-REF', 'EEG FP2-REF', 'EEG F3-REF', 'EEG F4-REF', 'EEG C3-REF', 'EEG C4-REF', 'EEG P3-REF', 'EEG P4-REF', 'EEG O1-REF', 'EEG O2-REF', 'EEG F7-REF', 'EEG F8-REF', 'EEG T3-REF', 'EEG T4-REF', 'EEG T5-REF', 'EEG T6-REF', 'EEG FZ-REF', 'EEG CZ-REF', 'EEG PZ-REF'], 'xyz_id': array([[ -29.4367,   83.9171,   -6.99  ],
       [  29.8723,   84.8959,   -7.08  ],
       [ -50.2438,   53.1112,   42.192 ],
       [  51.8362,   54.3048,   40.814 ],
       [ -65.3581,  -11.6317,   64.358 ],
       [  67.1179,  -10.9003,   63.58  ],
       [ -53.0073,  -78.7878,   55.94  ],
       [  55.6667,  -78.5602,   56.561 ],
       [ -29.4134, -112.449 ,    8.839 ],
       [  29.8426, -112.156 ,    8.8   ],
       [ -70.2629,   42.4743,  -11.42  ],
       [  73.0431,   44.4217,  -12.    ],
       [ -84.1611,  -16.0187,   -9.346 ],
       [  85.0799,  -15.0203,   -9.49  ],
       [ -72.4343,  -73.4527,   -2.487 ],
       [  73.0557,  -73.0683,   -2.54  ],
       [   0.3122,   58.512 ,   66.462 ],
       [   0.4009,   -9.167 ,  100.244 ],
       [   0.3247,  -81.115 ,   82.615 ]])}]
```

The error trace I get is below : 

```
Traceback (most recent call last):
  File "/global/u1/d/dyhan316/ECOG_AI/CBraMod/pretrain_main.py", line 296, in <module>
    main()
  File "/global/u1/d/dyhan316/ECOG_AI/CBraMod/pretrain_main.py", line 168, in main
    train_once_with_params(params)
  File "/global/u1/d/dyhan316/ECOG_AI/CBraMod/pretrain_main.py", line 213, in train_once_with_params
    trainer = Trainer(params, data_loader, model, valid_data_loader=valid_data_loader)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/u1/d/dyhan316/ECOG_AI/CBraMod/pretrain_trainer.py", line 48, in __init__
    summary(model,  input_data={"x": inputs, "data_info_list" : data_info_list, "use_mask": False}, depth=4, verbose = 1)
  File "/global/common/software/m4244/DIVER/lib/python3.12/site-packages/torchinfo/torchinfo.py", line 228, in summary
    summary_list, correct_input_size, get_total_memory_used(x), formatting
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/m4244/DIVER/lib/python3.12/site-packages/torchinfo/torchinfo.py", line 503, in get_total_memory_used
    result = traverse_input_data(
             ^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/m4244/DIVER/lib/python3.12/site-packages/torchinfo/torchinfo.py", line 436, in traverse_input_data
    k: traverse_input_data(v, action_fn, aggregate_fn)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/m4244/DIVER/lib/python3.12/site-packages/torchinfo/torchinfo.py", line 448, in traverse_input_data
    [traverse_input_data(d, action_fn, aggregate_fn) for d in data]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/m4244/DIVER/lib/python3.12/site-packages/torchinfo/torchinfo.py", line 436, in traverse_input_data
    k: traverse_input_data(v, action_fn, aggregate_fn)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/common/software/m4244/DIVER/lib/python3.12/site-packages/torchinfo/torchinfo.py", line 447, in traverse_input_data
    result = aggregate(
             ^^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```
