### ISSUE TITLE
summary seems to change model from cpu to gpu

### ISSUE THREAD

**Issue by yanshen0** [TylerYep/torchinfo#63]
Hi, 

I was using the summary function to inspect a torch model I created, but somehow each time I call `torchinfo.summary(model, ipt_shape)`, I get the following error

> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument mat1 in method wrapper_addmm)

My model is something like

`   

    def __init__(self, ipt_size, ipt_windows):
        super(l1lstm, self).__init__() 
        self.lstm1 = nn.LSTM(input_size=ipt_size, hidden_size=20, num_layers=2, batch_first=True) 
        self.lstm2 = nn.LSTM(input_size=20, hidden_size=20, num_layers=2, batch_first=True)
        self.lstm3 = nn.LSTM(input_size=20, hidden_size=10, num_layers=2, batch_first=True)
        self.lstm4 = nn.LSTM(input_size=10, hidden_size=10, num_layers=2, batch_first=True)
        self.lstm5 = nn.LSTM(input_size=10, hidden_size=10, num_layers=2, batch_first=True)

    def forward(self, x):
        x,_ = self.lstm1(x)
        x = x[:, -(x.shape[1]//2):, :]
        x,_ = self.lstm2(x) 
        x = x[:, -(x.shape[1]//2):, :]
        x,_ = self.lstm3(x)
        x = x[:, -(x.shape[1]//2):, :]
        x,_ = self.lstm4(x)
        x = x[:, -(x.shape[1]//2):, :]
        x,_ = self.lstm5(x)
        x = x[:, -100:, :]
        x = x.reshape(x.shape[0], -1)
        x = nn.LeakyReLU(inplace=False, negative_slope=0.01)(x)
        x = nn.Linear(x.shape[1], 500)(x)
        x = nn.LeakyReLU(inplace=False, negative_slope=0.01)(x)
        x = nn.Linear(500, 1)(x)
        return x
`

I checked the model before and after applying the summary function, the model was on cpu before summary, but on gpu after the summary. I didn't get this error previously when I define every layer in the init function, is this related? Thanks!

**Comment by TylerYep** [comment]
Torchinfo tries to automatically detect whether it should run in gpu or cpu.

To override this behavior, use:

```
summary(..., device = "cpu")
```
