### ISSUE TITLE
How to get full name of a layer?

### ISSUE THREAD

**Issue by saikatG** [TylerYep/torchinfo#70]
I am using the `summary` API to process the output sizes programmatically. 

Currently the `var_name` variable contains only the name of the current layer (e.g. `conv1`). Is there a way to get the full name (e.g. `layer1.layer2.conv1`?

I guess its easy to compute it by visiting the `parent_info` but would be a nice feature to have!

**Comment by TylerYep** [comment]
I believe `str(module.__class__)` is what you're looking for.

```
result = summary(module, ...)
for layer in result.summary_list:
    d = str(layer.module.__class__)
    print(d)
```

**Comment by saikatG** [comment]
No, that gives the classname of the layer, not the attribute name by which its defined in the model. 

For instance, `[name for name,mod in model.named_modules()]` gives the name of the layers in the model.

**Comment by TylerYep** [comment]
`summary_list` gives you access to each individual layer used when calling forward(), so you should be able to use your above code to get the full name.
