### ISSUE TITLE
summary() does not display reused activation in Sequential

### ISSUE THREAD

**Issue by seermer** [TylerYep/torchinfo#74]
**Describe the bug**
summary() does not display reused activation in Sequential

according to [this](https://discuss.pytorch.org/t/is-it-okay-to-reuse-activation-function-modules-in-the-network-architecture/74351/14), PyTorch allows reusing activation in a model, however, when reusing activation in a **sequential** model, summary() will skip all activations since the second time it is used. See the code below for more detail.

**To Reproduce**
```
from torchinfo import summary
from torch import nn
import torch

act = nn.LeakyReLU(inplace=True)


class Scale(nn.Module):
    def __init__(self):
        super(Scale, self).__init__()

    def forward(self, inputs):
        return inputs * (-3) + .1


model1 = nn.Sequential(act,
                       Scale(),
                       act,
                       Scale(),
                       act)

model2 = nn.Sequential(nn.LeakyReLU(inplace=True),
                       Scale(),
                       nn.LeakyReLU(inplace=True),
                       Scale(),
                       nn.LeakyReLU(inplace=True))

model3 = nn.Sequential(nn.LeakyReLU(inplace=True),
                       Scale(),
                       Scale())
summary(model1)
summary(model2)
summary(model3)

print(model1(torch.as_tensor([[1., -1., 0]])))
print(model2(torch.as_tensor([[1., -1., 0]])))
print(model3(torch.as_tensor([[1., -1., 0]])))
```

**Expected behavior**
as shown in the code above, three models are created.
model1 is a sequential model with lrelu-scale-lrelu-scale-lrelu, it reuses lrelu module (passing the same instance three times).
model2 is exactly the same as model1 except it doesn't reuse lrelu, it instead creates a new lrelu instance every time pass it in.
model3 is a model that only has lrelu at the beginning, which is different from model1 and model2. **If reusing activation is not allowed, model1 will be equivalent to model3 instead of model2**

in the end, we use summary() on all three models, and print output of all three models with the same input data

**expected**:  model1 and model2 have the same summary, model3 has different summary;
model1 and model2 have the same model output, model3 has different model output.

However, while model1 and model2 gives the same model output (which proves that reusing activation is allowed, model1 is equivalent to model2, different from model3), model1 displays the same summary as model3 (it skips reused activation)

**Screenshots**
output of above code
![image](https://user-images.githubusercontent.com/49250812/128596214-9cf5b6b1-03ef-49c3-8c60-bc14324161f6.png)

**note**: Scale is a custom module for demonstration purpose only, replacing with any layer will result in the same behavior that has no parameter, using Scale module allows easier tracking and demonstration because it does not involve any randomness.

**Comment by TylerYep** [comment]
Thank you for reporting this issue! This bug has been fixed in https://github.com/TylerYep/torchinfo/commit/8af8c6a266d3c327d225dc892ce76b0f507a8de7
and will be resolved in v1.5.3
