### ISSUE TITLE
Abstract quiet from verbose

### ISSUE THREAD

**Issue by AlessioQuercia** [TylerYep/torchinfo#75]
At the moment the way I use `summary()` is to store the result inside a variable and then save it to file (I don't really need to print it, therefore I choose verbose=0). I noticed that there is no direct way (please correct me if I am wrong, I am relatively a new user here) to store the maximum level of verbosity (2: weights and biases), without printing the entire model to stdout (since it would require to set verbose to 0).

It is probably not essential, but I was thinking that probably _quiet_ (0) verbose mode could be a stand-alone parameter (like print=True/False) or it could be removed and it would be up to the user to decide whether to print the result or not. In this way the method would be more flexible, and it would also easily allow to select verbose=2 without printing.

**Comment by TylerYep** [comment]
This is currently possible using the following code:
```
model_stats = torchinfo.summary(..., verbose=0)
model_stats.formatting.verbose = 2
# write str(model_stats) to a file
```
