### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [TylerYep/torchinfo#79]
**Is your feature request related to a problem? Please describe.**
It would be great to have a conda recipe to chain dependencies that need advanced requirements.

**Describe the solution you'd like**
Add a conda recipe.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by sarthakpati** [comment]
Already added: https://github.com/conda-forge/staged-recipes/pull/16039

**Comment by TylerYep** [comment]
Sounds good to me. Could you also add me as a recipe maintainer in your PR?

**Comment by sarthakpati** [comment]
Sure! Could you drop a comment in that PR?
