### ISSUE TITLE
different with torchsummary

### ISSUE THREAD

**Issue by ltm920716** [TylerYep/torchinfo#82]
hello，
 I use craft from https://github.com/clovaai/CRAFT-pytorch，

the torchsummary output is：
![image](https://user-images.githubusercontent.com/12007227/133239645-759cbbaf-4758-4c99-9e12-afd8f983be07.png)

the torchinfo output is：
![image](https://user-images.githubusercontent.com/12007227/133239431-409fa451-1b2d-4e58-8011-ca16e1229c1c.png)

there is a big different， please help

**Comment by TylerYep** [comment]
torchinfo should be more correct than torchsummary; torchsummary is not currently maintained. Feel free to reopen if you have any additional concerns.

**Comment by ltm920716** [comment]
hi, TylerYep
  this is a demo

`
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchinfo import summary as sm

device = torch.device('cpu')
num_classes = 10

class LeNet(nn.Module):
    def __init__(self, in_channels, num_classes):
        super(LeNet, self).__init__()
        self.conv1 = nn.Conv2d(in_channels, 20, kernel_size=5, stride=1)  # 20x24x24
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)  # 20x12x12
        self.conv2 = nn.Conv2d(20, 50, kernel_size=5, stride=1)  # 50x8x8
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)  # 50x4x4
        self.fc1 = nn.Linear(50 * 4 * 4, 500)  # 500
        self.fc2 = nn.Linear(500, num_classes)  # 10

    def forward(self, input):
        out = self.conv1(input)
        out = self.pool1(out)
        out = self.conv2(out)
        out = self.pool2(out)
        out = out.reshape(out.size(0), -1) 
        out = F.relu(self.fc1(out))
        out = self.fc2(out)
        return out

model = LeNet(1, num_classes).to(device)

sm(model, input_size=(1, 1, 28, 28))
`

here is the output：
![image](https://user-images.githubusercontent.com/12007227/133360130-2e4575fe-a745-4e6a-b4a4-797d7ee656ef.png)


and here is the ground-thurh：
  - Params: 520 + 25050 + 400500 + 5010 = 431080
  - Params_mem：431080 * (32/8) / 1024 / 1024 = 1.64 MB
  - Input_mem：1*28*28 *  (32/8) / 1024 / 1024 = 0.003 MB
  **_- forward_mem：(20*24*24 + 20*12*12 + 50*8*8 + 50*4*4 + 500 + 10)* (32/8) / 1024 / 1024 = 0.072 MB_**

So what the **Forward/backward pass size (MB): 0.12** means?  If I want to know the forward inference memory， could torchinfo show？ 

Thanks！

**Comment by TylerYep** [comment]
Note that memory calculation should be slightly more for a tensor, because torch.Tensor stores other information too, not just the 20x24x24 shape. We use `sys.getsizeof(tensor)` to get the most accurate size in MB, which works for all types of layers.

0.12 and 0.072 are close enough to explain the difference, but if you see an error in the calculation, feel free to open a PR!

**Comment by ltm920716** [comment]
@TylerYep 
Great，thanks！

**Comment by Yuxinyi-Qiyu** [comment]
hey, sorry to bother you.
I want to know how the "Params size" calculate.
the params are 431080, so the Params_mem：431080 * (32/8) / 1024 / 1024 = 1.64 MB, why the "Params size" is 1.72 instead of 1.64?

**Comment by mert-kurttutan** [comment]
> hey, sorry to bother you. I want to know how the "Params size" calculate. the params are 431080, so the Params_mem：431080 * (32/8) / 1024 / 1024 = 1.64 MB, why the "Params size" is 1.72 instead of 1.64?

Hi @Yuxinyi-Qiyu
What you are calculating is MiB, not MB
MB is calculated in terms of power of 10: 1MB= 10**6 B. So, the calculation done in source code: 431080 * (32/8) / 1000 / 1000 = 1.72

**Comment by Yuxinyi-Qiyu** [comment]
> > hey, sorry to bother you. I want to know how the "Params size" calculate. the params are 431080, so the Params_mem：431080 * (32/8) / 1024 / 1024 = 1.64 MB, why the "Params size" is 1.72 instead of 1.64?
> 
> Hi @Yuxinyi-Qiyu What you are calculating is MiB, not MB MB is calculated in terms of power of 10: 1MB= 10**6 B. So, the calculation done in source code: 431080 * (32/8) / 1000 / 1000 = 1.72

I got it!  thanks!!! 🥰
