### ISSUE TITLE
How to get output size when there are operations to reshape the tensor in `forward`

### ISSUE THREAD

**Issue by victkid** [TylerYep/torchinfo#83]
Is there a way to get the final output size from the `forward` function? The `summay` only returns the output size of layers which defined in `__init__`. 
```
class LSTMNet(nn.Module):
    """ Batch-first LSTM model. """
    def __init__(self, vocab_size=20, embed_dim=300, hidden_dim=512, num_layers=2):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.encoder = nn.LSTM(embed_dim, hidden_dim, num_layers=num_layers, batch_first=True)
        self.decoder = nn.Linear(hidden_dim, vocab_size)

    def forward(self, x):
        embed = self.embedding(x)
        out, hidden = self.encoder(embed)
        out = self.decoder(out)
        out = out.view(-1, out.size(2))
        return out, hidden

summary(
    LSTMNet(),
    (1, 100),
    dtypes=[torch.long],
    verbose=2,
    col_width=16,
    col_names=["kernel_size", "output_size", "num_params", "mult_adds"],
    row_settings=["var_names"],
)
```
For example, in the above network, the print out from `summary` looks like this
```
========================================================================================================
Layer (type (var_name))                  Kernel Shape     Output Shape     Param #          Mult-Adds
========================================================================================================
LSTMNet                                  --               --               --               --
├─Embedding (embedding)                  [300, 20]        [1, 100, 300]    6,000            6,000
│    └─weight                            [300, 20]                         └─6,000
├─LSTM (encoder)                         --               [1, 100, 512]    3,768,320        376,832,000
│    └─weight_ih_l0                      [2048, 300]                       ├─614,400
│    └─weight_hh_l0                      [2048, 512]                       ├─1,048,576
│    └─bias_ih_l0                        [2048]                            ├─2,048
│    └─bias_hh_l0                        [2048]                            ├─2,048
│    └─weight_ih_l1                      [2048, 512]                       ├─1,048,576
│    └─weight_hh_l1                      [2048, 512]                       ├─1,048,576
│    └─bias_ih_l1                        [2048]                            ├─2,048
│    └─bias_hh_l1                        [2048]                            └─2,048
├─Linear (decoder)                       [512, 20]        [1, 100, 20]     10,260           10,260
│    └─weight                            [512, 20]                         ├─10,240
│    └─bias                              [20]                              └─20
========================================================================================================
```
The last output shape I can get is [1, 100, 20], but there is an additional operation in `forward` (`out = out.view(-1, out.size(2))`) to change the shape from [1, 100, 20] to [100, 20]. Is there any way to get the final output size? Thanks

**Comment by TylerYep** [comment]
This is unfortunately not possible, because the model's forward hooks only capture layer information, and since reshaping is not a layer, torchinfo is unable to record this operation.

One feature that is possible is printing the final shape of the forward() function, but you can also do this yourself by copying the shape and appending it to the `torchinfo.summary().summary_list`. Let me know if you would like more details on this.

**Comment by victkid** [comment]
Thanks for your prompt reply! The reason that I want to get the output shape from `forward()` is because I want to create a function to automatically calculate the `input_size` for the next layer. 

I tried to create `self.output_shape = output.shape` in layer `forward()`, so I can access the output shape by using `layer.output_shape` after using `summary(layer, ...)`. But I had to remove this implementation since it's not compatible with jit conversion (do not know the reason why). 

I end up using a manual way to get the shape, something like. 
```
with torch.no_grad():
   output = layer(torch.randn(input_size))
output_shape = output.shape
```
Let me know if you have better ideas. I feel it is a nice feature have the output shape from `summary()`. Although the forward_hooks only capture layer information, `summary()` calls `forward()` and it should be able to get the output shape.

**Comment by TylerYep** [comment]
You can try:
```
model_statistics = summary(model, ...)
for layer_info in model_statistics.summary_list:
    print(layer_info.output_size)
```

Besides this, I have no plans to improve the layer capabilities from here. I'll review any PRs if you are interested in improving this, but no guarantees they'll be accepted. Thanks!
