### ISSUE TITLE
add __version__ string

### ISSUE THREAD

**Issue by cjekel** [TylerYep/torchinfo#88]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'm requesting `torchinfo.__version__` be a string pointing to the current version.

**Describe alternatives you've considered**
No.

**Additional context**

## Proposal

There are a couple ways to do this since you already have a single sourced version. I would suggest creating a `torchinfo/version.py` which would contain

```python
import pkg_resources

try:
    __version__ = pkg_resources.get_distribution('torchinfo').version
except Exception:
    __version__ = 'unknown'
```
which would then be imported in the main `__init__.py`.

There shouldn't be any problems with `python>=3.6`. Happy to send you a PR if you think this would be a nice feature.

**Comment by TylerYep** [comment]
Feel free to submit a PR adding this directly to __init__.py.

What is this variable used for?

**Comment by cjekel** [comment]
The variable `__version__` would just state your semantic version number from your setup.cfg.

A couple example use cases. I suspect I may have an outdated version in one of my many virtual environments. I can quickly check with `python -c "import torchinfo; print(torchinfo.__version__)"`. Can also be used to maintain support for depreciated APIs.
