### ISSUE TITLE
Add layer name / index in Layer description

### ISSUE THREAD

**Issue by arisliang** [TylerYep/torchinfo#94]
pytorch native print(model) produces the layer name/index. It's quite useful to cross check if torch summary has the same information in its output

`print(model)`:
![image](https://user-images.githubusercontent.com/1115503/140014961-5ceb847e-0f59-4bd0-bd68-b85f45377bb1.png)

**Describe the solution you'd like**
Add layer name / index in the torchsummary Layer column

`summary(model)`:
![image](https://user-images.githubusercontent.com/1115503/140015047-2e088398-42a0-4849-8a9f-13034f023675.png)

**Comment by TylerYep** [comment]
This is available via `torchinfo.summary(..., row_settings=["var_names"])`!
